version: '3.4'

networks:
   bridge:


services:
  freecourses.services.catalog:
    container_name: course-service
    image: ${DOCKER_REGISTRY-}freecoursesservicescatalog
    build:
      context: .
      dockerfile: Services/Catalog/FreeCourses.Services.Catalog/Dockerfile
    ports: 
     - 8000:80
    depends_on: 
        - mongo
        - sqlserver
    networks:
     - bridge
   
  mongo:
    container_name: mongo-db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
     - bridge

  sqlserver:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
     - 1433:1433 
    environment:
       - ACCEPT_EULA=Y
       - MSSQL_SA_PASSWORD=Usian@123
    #volumes:
    #  - sqlserver_data_container:/data/sql
    networks:
     - bridge
   
      
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    ports: 
     - 5001:80
    depends_on: 
        - sqlserver
    networks:
     - bridge

volumes:
  mongodb_data_container:
  sqlserver_data_container:
    

